# Generated by Django 2.2 on 2019-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='awards',
            field=models.ManyToManyField(blank=True, to='profiles.Award'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
